spring:
  application:
    name: transaction-practise
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trans?useSSL=false
    username: root
    password: P@ssw0rd

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 9080
logging:
  level:
    root: info
    org.springframework.orm.jpa: DEBUG